### PR TITLE
Geowave 228

### PR DESCRIPTION
**Pull request by chrisbennight**
#228

### CODE REVIEW

**Comment by rfecher** [comment]
Rather than adding a specific constant in each module of a "CHAR_SET" can you just use StringUtils.UTF8_CHAR_SET?  It is put in geowave-index because that is the lowest level dependency and each of the other modules can use it.

**Comment by chrisbennight** [comment]
That seems completely reasonable

**Comment by chrisbennight** [comment]
Moved it all over except for the ingest plugins instances;  it seems reasonable that the ingest plugins might need to declare their own input encoding (though in this case they were all UTF-8)

**Comment by rfecher** [comment]
fair enough, I don't think it really matters, but I didn't actually see why if the ingest-plugins were using UTF-8, that they wouldn't just re-use the constant for UTF-8 already defined in our string utilities...then again, does it really matter, no

**Comment by rfecher** [comment]
haha, I was just waiting for travis to finish and I was going to merge it this morning with the ingest plugin charsets, you didn't have to change it but thanks

**Pull request merged**
