### PR TITLE
Dependencies

### PR DESCRIPTION
**Pull request by andrewdmanning**

### CODE REVIEW

**Comment by andrewdmanning** [comment]
Pull request submitted to trigger Travis build - not necessarily ready to merge.

**Comment by rwgdrummer** [comment]
This request needs to be cleaned up.  There are too many files with 'return character' issues.

**Comment by dcy2003** [comment]
Simply merging with 0.9.1 to pick up the .gitattributes file should clean that up.

**Comment by andrewdmanning** [comment]
Will do. Also Travis doesn't seem to pass, so more work to be done. 

-Andrew

**Pull request closed without merging**
