### PR TITLE
Reduce vagrant geowave clone depth

### PR DESCRIPTION
**Pull request by chrisbennight**

### CODE REVIEW

**Comment by chrisbennight** [comment]
#323

**Comment by chrisbennight** [comment]
@jwomeara

**Comment by jwomeara** [comment]
The change is fine with me.  It all depends on how we expect the vagrant setup to be used.  If it's just for checking things out, a minimal history is fine.  However, if we want people to use it as a dev environment, we might want the full history.  

I think at this point the jdk download is the most time consuming task.

**Comment by chrisbennight** [comment]
do you need the full history to develop?  I think you can still do a branch and work like normal, no?  I'll test it real quick

**Comment by jwomeara** [comment]
If that's the case, then merge away.

**Comment by chrisbennight** [comment]
https://github.com/ngageoint/geowave/tree/shallow_clone_test

**Pull request merged**
