### PR TITLE
Ap casanamo mapreduce

### PR DESCRIPTION
**Pull request by akash-peri**
This adds support for MapReduce to DynamoDB
Note: This gets one of the two tests in BasicMapReduceIT working; the other one fails due to an issue with adapter ids that was fixed for HBase; a similar fix needs to be applied here

### CODE REVIEW

**Comment by akash-peri** [comment]
Travis failed; need to investigate

**Comment by rfecher** [comment]
yes, I'd suggest disabling DynamoDB support for BasicMapReduceIT until we get that other test straightened out.  Also, it looks like it failed before it got to that point based on a findbugs issue.  Make sure you can run `mvn verify` in extensions/datastores/dynamodb (it'll probably fail right now and show the details of the findbugs issue).

**Comment by rfecher** [comment]
is this superceded by PR #1057?  Can we close this one?

**Comment by akash-peri** [comment]
Yep, we can.

**Pull request closed without merging**
