### PR TITLE
Geowave 274 image thumbnails

### PR DESCRIPTION
**Pull request by spohnan**
* Addresses #274 and halves the size of our documentation and site images from ~7.5MB down to ~3.5MB
* Addresses #268 and updates the build to create docs, site and javadocs in the right order when mvn install -P docs is run
* Cleaned up and updated the docs pom. Made note that due to an upstream issue PDFs will not include images when built from Windows as reported by @rwgdrummer . At the point it gets fixed upstream I'll update our plugin.
* Fixed link used to directly download an RPM from the artifact listing page

### CODE REVIEW

**Comment by chrisbennight** [comment]
Restarted the jobs that glitched in travis, but looks good.   One small request - could you squash those commits for this PR (down to one).

**Comment by spohnan** [comment]
rebased to pick up recent merges and squashed into a single commit

**Comment by chrisbennight** [comment]
Hm, that first test keeps failing - though I don' see hwo this pull request would have caused it.  The error though points to a verison mismatch in the gs-web-app 


```
jar:file:/home/travis/build/ngageoint/geowave/geowave-test/target/geoserver/WEB-INF/lib/gs-main-2.6.2.jar!/applicationContext.xml]: 
Cannot resolve reference to bean 'resourceLoader' while setting constructor argument; 
  nested exception is org.springframework.beans.factory.BeanCreationException: 
    Error creating bean with name 'resourceLoader' defined in URL   
      [jar:file:/home/travis/build/ngageoint/geowave/geowave-test/target/geoserver/WEB-INF/lib/gs-main-2.6.2.jar
```

2.6.2 is wrong for this test - should be 2.5.5

**Comment by jwomeara** [comment]
Are we pulling a system property for the geoserver version directly in a
child pom?  That's the issue we had before and we fixed it by specifying
versions through dependency management in the parent pom. I am not by a
computer at the moment, but I can check tomorrow.

**Comment by rfecher** [comment]
I see nothing in this commit that should cause travis issues on gs-web-app.  Let's see if other builds consistently have this issue too.  I have a build matrix running in travis right now.

**Comment by jwomeara** [comment]
I left a note on the line of code that I believe is causing the problem.  It was pulled with merge request #281

**Comment by jwomeara** [comment]
Actually, generally I see that in the test pom, the geoserver.version property is used in a bunch of places.  It shouldn't be as this defeats the purpose of dependency management.  By doing this I think that we are forcing the test pom to ignore the system property specified on the command line and instead it is using the default value specified in the parent pom.  If this is the real cause of the issue, then we just need to remove the version specifier from all of the geoserver dependencies...  I also think this is my goof as the commit log shows that it's been this way since I did the initial commit...

**Comment by rfecher** [comment]
the strange thing is that this commit seems harmless

**Comment by jwomeara** [comment]
Maybe the new geotools release affected the older jars in the boundless
repo...?

**Comment by chrisbennight** [comment]
I deleted all travis caches in case there was something old in there; when I run the same build locally there's no 2.6x jar's in the lib directory.

**Comment by spohnan** [comment]
will remove all pom and build script changes and resubmit so this truly just updates images and web pages. A second pull request will be used to isolate any possible problems with other changes.

**Pull request closed without merging**
