### PR TITLE
Added GeoTools query example

### PR DESCRIPTION
**Pull request by dcy2003**
GeoTools query example for #116

### CODE REVIEW

**Comment by chrisbennight** [comment]
Didn't dig into the code, but from looking at the errors it looks like you might need to add a maven munge directive here - seems there might by a method being called that's not valid for accumulo 1.5

**Comment by rfecher** [comment]
I didn't see it that way, at least in the last failure what I saw was it failing on a random zookeeper transaction related test unrelated to this example code.  I think there's at least two random failures in our tests, I ticketed one #361 and I probably should have added an issue for this before restarting.  We'll probably see it again.

**Comment by chrisbennight** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project geowave-example: Compilation failure
[ERROR] /home/travis/build/ngageoint/geowave/examples/src/main/java/mil/nga/giat/geowave/examples/query/GeotoolsQueryExample.java:[133,14] error: cannot find symbol
```

line 133 is 
https://github.com/ngageoint/geowave/blob/GEOWAVE-116_1/examples/src/main/java/mil/nga/giat/geowave/examples/query/GeotoolsQueryExample.java#L133

or 
```
accumulo.getConnector(	ACCUMULO_USER, ACCUMULO_PASSWORD)
```
where accumulo is org.apache.accumulo.minicluster.MiniAccumuloCluster

the getConnector method is marked as "since 1.6.0"
https://github.com/apache/accumulo/blob/master/minicluster/src/main/java/org/apache/accumulo/minicluster/MiniAccumuloCluster.java#L110

.


I think I win! :)

**Comment by jwomeara** [comment]
We test against 1.5.2 in travis.  :)

https://github.com/ngageoint/geowave/blob/master/.travis.yml#L7

Munge it up, brother!

**Comment by chrisbennight** [comment]
To be fair, could possibly skip munge and just go with a 1.5 compatible method if it wasn't deprecated.

Hopefully when 1.7 get's out we can cute some of hte 1.5 support.

**Comment by rfecher** [comment]
@chrisbennight you win this time ;)

I don't know what I was looking at with the transaction stuff - I'll just stick to the claim that the one test I had restarted happened to have the random issue before it got to compiling the examples.

**Comment by dcy2003** [comment]
Sorry for the oversight - should be fixed now.  I took @chrisbennight recommended approach and simply avoided the use of a 1.6-only method.

**Pull request merged**
