### PR TITLE
Updated Jace/PDAL/Mapnik documentation

### PR DESCRIPTION
**Pull request by jwomeara**

### CODE REVIEW

**Comment by drew-bower** [comment]
Nice!

**Comment by jwomeara** [comment]
I'm pretty excited to get this out there. I just hope the Mapnik folks are happy with our pull request. I'm going to play around with mapbox studio sometime this weekend to see if I can get an an end to end test with GeoWave working.

**Comment by drew-bower** [comment]
Can you send a reference to your PR?

**Comment by drew-bower** [comment]
Oh wait I guess it's here. I guess I need to look a little closer.

**Comment by chrisbennight** [comment]
Here's the mapnik pull request if that's what you were looking for:
https://github.com/mapnik/mapnik/pull/2758

**Pull request merged**
