### PR TITLE
0.9.1

### PR DESCRIPTION
**Pull request by rfecher**
here's the diff between the branch and master - do we want to pull it across to master?

### CODE REVIEW

**Comment by datasedai** [comment]
Can we hold off until the last few pull requests are in?

**Comment by rfecher** [comment]
makes sense, it looks like there's already conflicts that need resolving.

**Comment by datasedai** [comment]
Edit: I forgot about bills change too for Stanag.

**Comment by rwgdrummer** [comment]
I would redo this branch.  It is already behind 0.9.1

**Comment by dcy2003** [comment]
Closing this PR based on discussions this morning.

**Pull request closed without merging**
